config/routes.rb
MySite::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'site#home'
  get "/projects" => "projects#index", as: "projects"
  get "/profile" => "profiles#show", as: "profile"
  get "/artwork" => "site#artwork"

  resources :projects, only: [:show]
  resources :profiles, only: [:show]
  resources :work_experiences, only: [:show, :index]
  resources :life_experiences, only: [:show, :index]
  resources :blog_posts, only: [:show, :index]
  resources :freelance_jobs, only: [:new, :create]

  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  rails_admin do
  end
end

app/models/freelance_job.rb
class FreelanceJob < ActiveRecord::Base
  rails_admin do
  end

end

app/models/life_experience.rb
class LifeExperience < ActiveRecord::Base
  rails_admin do
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  rails_admin do
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  rails_admin do
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  rails_admin do 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work_experience.rb
class WorkExperience < ActiveRecord::Base
  rails_admin do
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find_by_key('Billy')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end

  def index
    @projects = Project.all
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  layout :choose_layout
  def home
  end

  def profile
    @profile = Profile.find_by_key('Billy')
  end

  def artwork
  end

  def choose_layout
    case action_name
    when 'home'
      'application'
    else
      'artwork'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/freelance_jobs_helper.rb
module FreelanceJobsHelper
end

app/helpers/life_experiences_helper.rb
module LifeExperiencesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]>
<!-->
<html lang="en">
<!--<![endif]-->
%head
  %meta{:charset => "utf-8"}
  %link{:rel  => "icon", :type => "image/x-icon", :href =>"/favicon.ico"}
  %title= "Billy Irwin"
  = stylesheet_link_tag 'application'
  = csrf_meta_tags
  = javascript_include_tag 'application'
%body
  .cell.tall
    .content-wrapper
      .content-col-300
        .cell-section
          = yield
    .left-col-300
      .left-nav
        = render "shared/hero"
        .social-icons
          .icon.fb
          .icon.tw
          .icon.li
          .icon.gh

app/views/layouts/artwork.html.haml
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]>
<!-->
<html lang="en">
<!--<![endif]-->
%head
  %meta{:charset => "utf-8"}
  %link{:rel  => "icon", :type => "image/x-icon", :href =>"/favicon.ico"}
  %title= "Billy Irwin"
  = stylesheet_link_tag 'application'
  = csrf_meta_tags
  = javascript_include_tag 'application'
%body
  = yield

app/views/notifier/new_job.html.haml
= @gig.name
= @gig.email
= @gig.description

app/views/shared/_hero.html.haml
.row-fluid
  .hero-title 
    B
.row-fluid
  .span10.nav-area
    %ul
      %li
        = link_to root_url do
          .nav-box.home-nav
          .nav-title
            Home
      %li
        = link_to projects_url do
          .nav-box.portfolio-nav
          .nav-title 
            Portfolio
      %li
        = link_to blog_posts_url do
          .nav-box.blog-nav
          .nav-title 
            Blog
      %li
        = link_to life_experiences_url do
          .nav-box.life-nav
          .nav-title 
            Life
      %li
        = link_to new_freelance_job_path do
          .nav-box.work-nav
          .nav-title 
            Work

app/views/shared/_project_hero.html.haml
.inner-container
  .row-fluid.hero-row
    .span10
      .hero-title 
        Title goes here
    .span2.nav-area
      = link_to root_url do
        .nav-box.home-nav
          /.nav-title 
           / Home
      = link_to projects_url do
        .nav-box.portfolio-nav
          /.nav-title 
          /  Portfolio
      = link_to blog_posts_url do
        .nav-box.blog-nav
         / .nav-title 
          /  Blog
      = link_to life_experiences_url do
        .nav-box.life-nav
          /.nav-title 
           / Life
      = link_to profile_url do
        .nav-box.work-nav
          /.nav-title 
           / Work