config/routes.rb
MySite::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'site#home'
  get "/projects" => "projects#index", as: "projects"
  get "/profile" => "profiles#show", as: "profile"
  get "/artwork" => "site#artwork"

  resources :projects, only: [:show]
  resources :profiles, only: [:show]
  resources :work_experiences, only: [:show, :index]
  resources :life_experiences, only: [:show, :index]
  resources :blog_posts, only: [:show, :index]
  resources :freelance_jobs, only: [:new, :create]

  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  rails_admin do
  end
end

app/models/freelance_job.rb
class FreelanceJob < ActiveRecord::Base
  rails_admin do
  end

end

app/models/life_experience.rb
class LifeExperience < ActiveRecord::Base
  rails_admin do
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  rails_admin do
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  rails_admin do
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base

  rails_admin do 
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work_experience.rb
class WorkExperience < ActiveRecord::Base
  rails_admin do
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :save_location

  private
    def save_location
      session[:back] = session[:tmp_url] || root_url
      session[:tmp_url] = request.url
    end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/freelance_jobs_controller.rb
class FreelanceJobsController < ApplicationController
  def new
    @freelance = FreelanceJob.new
  end

  def create
    @freelance = FreelanceJob.new(params.require(:freelance_job).permit(:name, :email, :description))
    if @freelance.save
      Notifier.new_job(@freelance).deliver
      redirect_to root_url
    else
      redirect_to new_freelance_job_path
    end
  end

end

app/controllers/life_experiences_controller.rb
class LifeExperiencesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find_by_key('Billy')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end

  def index
    @projects = Project.all
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  layout :choose_layout
  def home
  end

  def profile
    @profile = Profile.find_by_key('Billy')
  end

  def artwork
  end

  def choose_layout
    case action_name
    when 'home'
      'application'
    else
      'artwork'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/freelance_jobs_helper.rb
module FreelanceJobsHelper
end

app/helpers/life_experiences_helper.rb
module LifeExperiencesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
end

app/views/blog_posts/index.html.haml
%h1 BlogPosts#index
%p Find me in app/views/blog_posts/index.html.haml

app/views/blog_posts/show.html.haml
%h1 BlogPosts#show
%p Find me in app/views/blog_posts/show.html.haml

app/views/freelance_jobs/new.html.haml
= form_for(@freelance) do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :email
  = f.text_field :email
  %br
  = f.label :description
  = f.text_area :description
  %br
  = f.submit

app/views/life_experiences/index.html.haml
%h1 LifeExperiences#index
%p Find me in app/views/life_experiences/index.html.haml

app/views/life_experiences/show.html.haml
%h1 LifeExperiences#show
%p Find me in app/views/life_experiences/show.html.haml

app/views/profiles/show.html.haml
.box.medium.faded
  = @profile.slogan

.box.medium.faded
  = @profile.bio

app/views/projects/index.html.haml
- @projects.each do |p|
  =link_to project_path(p) do
    .box.small.faded
      .box-title 
        = p.name

app/views/projects/show.html.haml
.box.medium.faded
  = @project.description

.box.medium.faded
  .video-wrapper
    = @project.video_link.html_safe